obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/

#ifdef VENDOR_EDIT
#yichun chen@BSP.CHG.Basic, 2018/4/27  Add for OPPO_CHARGE
obj-$(CONFIG_OPPO_CHARGE_450_O) += oppo/
#endif

obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_ARCH_QCOM)		+= qcom/
obj-$(CONFIG_ARCH_QCOM)		+= qcom/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
